name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  check_version:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get-version.outputs.version }}
      LAST_TAG: ${{ steps.last_release.outputs.tag_name }}

    steps:
      - name: check repository
        uses: actions/checkout@v4
    
      - uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: Core/Core.csproj
          
      - name: "get-last-release"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
         
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    needs: check_version
    if: ${{ needs.check_version.outputs.LAST_TAG == needs.check_version.outputs.VERSION }}
    strategy:
      matrix:
        folder: [Elib2EbookCli, Elib2EbookWeb]
          
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ matrix.folder }}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          file: "${{ matrix.folder }}/Dockerfile"
          push: true
          tags: onlyfart/${{ steps.string.outputs.lowercase }}:${{ needs.check_version.outputs.VERSION }},onlyfart/${{ steps.string.outputs.lowercase }}:latest
