name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
          
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: Core/Core.csproj
          
      - name: "get-last-release"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}

      - name: build and push docker image to registry
        if: ${{ steps.last_release.outputs.tag_name == steps.get-version.outputs.version }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          file: "Elib2EbookCli/Dockerfile"
          push: true
          tags: onlyfart/elib2ebookcli:${{steps.get-version.outputs.version}}

      - name: build and push docker image to registry
        if: ${{ steps.last_release.outputs.tag_name == steps.get-version.outputs.version }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          file: "Elib2EbookCli/Dockerfile"
          push: true
          tags: onlyfart/elib2ebookcli:latest
          
      - name: build and push docker image to registry
        if: ${{ steps.last_release.outputs.tag_name == steps.get-version.outputs.version }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          file: "Elib2EbookWeb/Dockerfile"
          push: true
          tags: onlyfart/elib2ebookweb:${{steps.get-version.outputs.version}}

      - name: build and push docker image to registry
        if: ${{ steps.last_release.outputs.tag_name == steps.get-version.outputs.version }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          file: "Elib2EbookWeb/Dockerfile"
          push: true
          tags: onlyfart/elib2ebookweb:latest
