name: .NET-test

on: push

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Small
      run: >
        dotnet publish -c release -p:PublishDir=../dist/small --no-self-contained 
        -p:PublishSingleFile=true -p:DebugType=embedded -p:PublishTrimmed=false 
        -p:EnableCompressionInSingleFile=false --use-current-runtime Elib2EbookCli
    - name: Portable
      run: >
        dotnet publish -c release -p:PublishDir=../dist/portable --self-contained 
        -p:PublishSingleFile=true -p:DebugType=embedded -p:PublishTrimmed=true -p:TrimMode=partial
        -p:EnableCompressionInSingleFile=true --use-current-runtime Elib2EbookCli

    - uses: actions/upload-artifact@v3
      with:
        name: Elib2Ebook-${{ matrix.os }}
        path: ${{ github.workspace }}/dist/small

    - uses: actions/upload-artifact@v3
      with:
        name: Elib2Ebook-${{ matrix.os }}-portable
        path: ${{ github.workspace }}/dist/portable
